#Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Social Connection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Social Connection
  pod 'DittoSyncKitSwift', '~> 1.0.0-alpha7'
  pod 'Eureka'
end
